In [2]:
from __future__ import print_function
import torch

In [3]:
#创建一个没有初始化的5*3的矩阵
x = torch.empty(5,3)
print(x)

tensor([[1.0194e-38, 9.0919e-39, 8.4490e-39],
        [1.0653e-38, 9.9184e-39, 8.4490e-39],
        [8.9082e-39, 8.9082e-39, 8.7245e-39],
        [1.0653e-38, 9.9184e-39, 8.4490e-39],
        [9.2755e-39, 9.0919e-39, 4.2246e-39]])


In [4]:
#创建一个随机初始化矩阵
x = torch.rand(5,3)
print(x)

tensor([[0.1166, 0.6203, 0.4609],
        [0.5085, 0.3294, 0.4124],
        [0.9474, 0.8438, 0.4967],
        [0.0128, 0.4174, 0.6389],
        [0.7048, 0.5635, 0.7776]])


In [10]:
#构建一个填满0且数据类型为long的矩阵
x = torch.zeros(5,3,dtype = torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [11]:
#直接从数据构造张量
x = torch.tensor([5.5,3])
print(x)

tensor([5.5000, 3.0000])


In [12]:
#或者根据已有的tensor建立新的tensor。除非用户提供新的值，否则这些方法重用输出张量的属性
x = x.new_ones(5,3,dtype=torch.double)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [13]:
#重载dtye
x = torch.randn_like(x,dtype = torch.float)
print(x)

tensor([[-0.0129, -0.1135,  0.5958],
        [ 1.0837,  0.5546, -1.2106],
        [-1.6410, -0.0768, -0.5514],
        [ 0.9579, -0.7540,  2.2380],
        [-0.3332, -0.2957,  0.1051]])


In [14]:
#获取张量的形状
print(x.size())

torch.Size([5, 3])


In [17]:
#运算
#加法——形式1
y = torch.rand(5,3)
print(x+y)
print(y)

tensor([[ 0.6601,  0.1857,  1.0605],
        [ 1.6179,  0.5553, -0.2195],
        [-0.8634,  0.5245, -0.2882],
        [ 1.6096, -0.6755,  3.0255],
        [ 0.3553,  0.5138,  0.3309]])
tensor([[6.7304e-01, 2.9926e-01, 4.6473e-01],
        [5.3422e-01, 7.2008e-04, 9.9110e-01],
        [7.7766e-01, 6.0121e-01, 2.6326e-01],
        [6.5168e-01, 7.8432e-02, 7.8753e-01],
        [6.8847e-01, 8.0944e-01, 2.2580e-01]])


In [18]:
#加法——形式2
print(torch.add(x,y))

tensor([[ 0.6601,  0.1857,  1.0605],
        [ 1.6179,  0.5553, -0.2195],
        [-0.8634,  0.5245, -0.2882],
        [ 1.6096, -0.6755,  3.0255],
        [ 0.3553,  0.5138,  0.3309]])


In [19]:
#加法——形式3,给定一个输出参量组作为参数
result = torch.empty(5,3)
torch.add(x,y,out = result)
print(result)

tensor([[ 0.6601,  0.1857,  1.0605],
        [ 1.6179,  0.5553, -0.2195],
        [-0.8634,  0.5245, -0.2882],
        [ 1.6096, -0.6755,  3.0255],
        [ 0.3553,  0.5138,  0.3309]])


In [20]:
#加法——原地/原位操作
y.add_(x)
print(y)

tensor([[ 0.6601,  0.1857,  1.0605],
        [ 1.6179,  0.5553, -0.2195],
        [-0.8634,  0.5245, -0.2882],
        [ 1.6096, -0.6755,  3.0255],
        [ 0.3553,  0.5138,  0.3309]])


In [21]:
#注意：任何一个in-place改变张量的操作后面都固定一个_。
#也可以像NumPy一样的各种索引操作
print(x[:,1]);
#这里是输出了x的第二列

tensor([-0.1135,  0.5546, -0.0768, -0.7540, -0.2957])


In [22]:
#改变形状：如果想改变形状，可以使用torch.view
x = torch.randn(4,4)
y = x.view(16)
z = x.view(-1,8)
print(x.size(),y.size(),z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [23]:
#如果仅是包含一个元素的tensor，可以使用.item()来得到对应的python数值
x = torch.randn(1)
print(x)
print(x.item())

tensor([-0.2461])
-0.24609006941318512


In [ ]:
#当然，tensor还有成百中运算操作，包括转置，索引，切片，数学运算，线性代数，随机数等
#链接：

In [ ]:
#桥接;Numpy
#将一个Torch张量转换为一个Numpy数组是轻而易举的事情，反之亦然
#Torch张量和Numpy数组将共享它们的底层内存位置，因此当一个改变时，另外一个也会改变

In [24]:
#将torch的Tensor转化为Numpy数组
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [25]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [26]:
#来看看Numpy是如何改变里面的值的
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [27]:
#将Numpy数组转化为Torch张量

#看改变Numpy数组是如何自动改变Torch张量的

import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a,1,out = a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [28]:
#CPU上的所有张量（Char Tensor除外）都支持与Numpy的相互转换
#CUDA上的张量
#张量可以使用.to方法移动到任何设备（device）上：
#如果有GPU 的同学可以去试试