In [ ]:
# Autograd :自动求导
#Pytorch中，所有神经网络的核心是autograd包
#autograd包为张量上的所有操作提供了自动求导机制。它是一个在运行时定义的框架

In [ ]:
#张量 torch.Tensor是这个包的核心类，如果设置它的属性 .requeires_grad为True,那么它将追踪对于该张量的所有操作
#当完成计算后可以通过调用 .backward(),来自动计算所有的梯度
#这个张量的所有梯度将会自动累加到.grad属性
#.datach()方法：将其与计算历史分离，并阻止它未来的计算记录被跟踪，要阻止一个张量被跟踪历史，可以调用
#with torch.no_grad():防止跟踪历史记录（和使用内存）
#requires_grad = True ：这个是模型可能具有的可训练的参数，但是我们不需要在此过程中对他们进行梯度计算
#Function类：其和Tensor互相连接生成了一个无圈图（没有简单回路），它编码了完整的计算历史
#.grad_fn属性，该属性引用了创建Tensor自身的Function(除非)这个张量是手动创建的
#.backward()：计算导数

In [2]:
import torch

In [4]:
#创建一个张量并设置requires_grad = True用来追踪其计算历史
x = torch.ones(2,2,requires_grad = True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [5]:
#对这个张量做一次运算
y = x + 2
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [6]:
#y是计算的结果，所以他有grad_fn属性
print(y.grad_fn)

In [13]:
#对其进行更多操作
z = y*y*3
out = z.mean()
print(z,out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)


In [14]:
#.requires_grad()原地改变了现有张量的requires_grad标志。如果没有指定的话，默认输入的这个标志是False
a = torch.randn(2,2)
a = ((a*3)/(a-1))
print(a.requires_grad)
a.requires_grad_(True)
print(a.requires_grad)
b = (a*a).sum()
print(b.grad_fn)

False
True


In [15]:
#梯度——进行反向传播
out.backward()

In [16]:
print(x.grad)

tensor([[9., 9.],
        [9., 9.]])


In [ ]:
#通常来说，torch.autograd是计算雅可比向量积的一个“引擎”
#也就是说，给定任意向量，计算乘积

In [17]:
#计算雅可比向量积的例子
x = torch.randn(3, requires_grad=True)

y = x * 2
while y.data.norm() < 1000:
    y = y * 2

print(y)

tensor([-387.8191, -221.6898, 1336.2773], grad_fn=<MulBackward0>)


In [ ]:
#在这种情况下，y 不再是标量。torch.autograd 不能直接计算完整的雅可比矩阵，但是如果我们只想要雅可比向量积，只需将这个向量作为参数传给 backward

In [18]:
v = torch.tensor([0.1, 1.0, 0.0001], dtype=torch.float)
y.backward(v)

print(x.grad)

tensor([1.0240e+02, 1.0240e+03, 1.0240e-01])


In [ ]:
#也可以通过将代码块包装在 with torch.no_grad(): 中，来阻止autograd跟踪设置了 .requires_grad=True 的张量的历史记录。

In [19]:
print(x.requires_grad)
print((x ** 2).requires_grad)

with torch.no_grad():
    print((x ** 2).requires_grad)

True
True
False
